openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: https://localhost:8443
  description: Generated server url
paths:
  /book/{id}/{seats}:
    put:
      tags:
      - booking-controller
      operationId: updateSeatsById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: seats
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Booking'
  /screens/search:
    post:
      tags:
      - screen-search-controller
      operationId: searchResult
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JsonNode'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /screens/saveAll:
    post:
      tags:
      - screen-search-controller
      operationId: saveAllScreens
      requestBody:
        content:
          application/json:
            schema:
              type: object
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /book/{screenId}/{date}/{seats}:
    post:
      tags:
      - booking-controller
      operationId: bookSeats
      parameters:
      - name: screenId
        in: path
        required: true
        schema:
          type: string
      - name: date
        in: path
        required: true
        schema:
          type: string
      - name: seats
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: integer
                format: int32
  /screen/checkAvailability/{id}/{date}:
    get:
      tags:
      - screen-controller
      operationId: checkAvailability
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: date
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TicketAvailability'
  /book/{id}:
    get:
      tags:
      - booking-controller
      operationId: getBookingDetailsById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Booking'
    delete:
      tags:
      - booking-controller
      operationId: deleteById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Booking'
components:
  schemas:
    Booking:
      type: object
      properties:
        id:
          type: integer
          format: int32
        screenId:
          type: integer
          format: int32
        date:
          type: string
          format: date
        seatsBooked:
          type: integer
          format: int32
        active:
          type: boolean
    JsonNode:
      type: object
    TicketAvailability:
      type: object
      properties:
        screenId:
          type: integer
          format: int32
        screenName:
          type: string
        totalCapacity:
          type: integer
          format: int32
        seatsBooked:
          type: integer
          format: int32
        seatsAvailable:
          type: integer
          format: int32
