@startuml Two Modes - Technical View
' Uncomment the line below for "dark mode" styling
'!$AWS_DARK = true
!include <C4/C4_Container>
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v18.0/dist
!define AWSPUML https://raw.githubusercontent.com/milo-minderbinder/AWS-PlantUML/release/18-2-22/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/AWSSimplified.puml
!include AWSPuml/Compute/EC2.puml
!include AWSPuml/Compute/EC2Instance.puml
!include AWSPuml/Storage/SimpleStorageService.puml
!include AWSPuml/Groups/AWSCloud.puml
!include AWSPuml/Groups/VPC.puml
!include AWSPuml/Groups/AvailabilityZone.puml
!include AWSPuml/Groups/PublicSubnet.puml
!include AWSPuml/Groups/PrivateSubnet.puml
!include AWSPuml/NetworkingContentDelivery/VPCNATGateway.puml
!include AWSPuml/NetworkingContentDelivery/VPCInternetGateway.puml
!includeurl AWSPuml/Containers/ElasticKubernetesService.puml
!include AWSPuml/AWSCommon.puml
!includeurl AWSPUML/common.puml
!includeurl AWSPUML/ApplicationServices/AmazonAPIGateway/AmazonAPIGateway.puml
!includeurl AWSPUML/Compute/AWSLambda/AWSLambda.puml
!includeurl AWSPUML/Compute/AWSLambda/LambdaFunction/LambdaFunction.puml
!includeurl AWSPUML/Database/AmazonDynamoDB/AmazonDynamoDB.puml
!includeurl AWSPUML/Database/AmazonDynamoDB/table/table.puml
!includeurl AWSPUML/General/AWScloud/AWScloud.puml
!include AWSPuml/Containers/EKSCloud.puml
!includeurl AWSPUML/General/client/client.puml
!includeurl AWSPUML/General/user/user.puml
!includeurl AWSPUML/SDKs/JavaScript/JavaScript.puml
!includeurl AWSPUML/Storage/AmazonS3/AmazonS3.puml
!includeurl AWSPUML/Storage/AmazonS3/bucket/bucket.puml

' Uncomment the following line to create simplified view
' !include AWSPuml/AWSSimplified.puml

!include AWSPuml/General/Users.puml
!include AWSPuml/ApplicationIntegration/APIGateway.puml
!include AWSPuml/ApplicationIntegration/APIGateway.puml
!include AWSPuml/SecurityIdentityCompliance/Cognito.puml
!include AWSPuml/Compute/Lambda.puml
!include AWSPuml/Compute/EC2AWSMicroserviceExtractorforNET.puml
!include AWSPuml/Database/DynamoDB.puml

left to right direction

Users(sources, "CLIENT", "Browser/Mobile")
AWSCloudGroup(cloud) {
Container(ddos, "DDoS/WAF", "FIREWALL")
  VPCGroup(vpc) {
    Container(alb, "NETWORK", "LOAD BALANCER")
        EKSCloud(eks, "EKS", "container orchestration") {
        rectangle "$APIGatewayIMG()\nKONG API\nGateway Cluster" as api
        rectangle "$EC2AWSMicroserviceExtractorforNETIMG()\nKeyCloak SVC" as kc
        rectangle "$EC2AWSMicroserviceExtractorforNETIMG()\nOnBoarding SVC" as ob
        rectangle "$EC2AWSMicroserviceExtractorforNETIMG()\nUser/Cust SVC" as cust
        rectangle "$EC2AWSMicroserviceExtractorforNETIMG()\nSearch SVC" as search
        rectangle "$EC2AWSMicroserviceExtractorforNETIMG()\nBooking SVC" as book
        rectangle "$EC2AWSMicroserviceExtractorforNETIMG()\nPayment SVC" as pay
        rectangle "$EC2AWSMicroserviceExtractorforNETIMG()\nNotification SVC" as noti
        rectangle "$EC2AWSMicroserviceExtractorforNETIMG()\nReporting SVC" as rep
        }
  }
  Container(cdn, "CDN", "CONTENT")
  rectangle "$SimpleStorageServiceIMG()\nS3" as objstore
  Container(redis, "REDIS", "Distributed Cache")
  Container(rds, "RDS", "Datastore")
  Container(es, "ElasticSearch/Solr", "Search Engine")
  Container(solace, "Solace/RabbitMQ", "PubSub")
  Container(mongo, "MongoDB", "NoSQL")
}
sources --> ddos
ddos --> alb
alb --> api
@enduml